# Generated by Django 4.0.1 on 2022-05-13 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicacionesApp', '0016_post_disponibilidad_post_precio'),
        ('pagosApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='publicacionesApp.post'),
        ),
    ]
