# Generated by Django 4.0.1 on 2022-03-31 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacionesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='foto',
            field=models.URLField(default='null', max_length=300),
        ),
    ]
