# Generated by Django 4.0.1 on 2022-04-08 22:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publicacionesApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='nombres',
        ),
        migrations.AddField(
            model_name='autor',
            name='usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.PositiveIntegerField(default=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('texto', models.CharField(max_length=250, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('update', models.DateField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='publicacionesApp.autor')),
            ],
        ),
    ]
