# Generated by Django 4.0.1 on 2022-04-08 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacionesApp', '0002_remove_autor_apellido_remove_autor_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='nickname',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
