# Generated by Django 4.0.1 on 2022-04-08 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicacionesApp', '0003_autor_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='foto',
        ),
    ]
