# Generated by Django 4.0.1 on 2022-04-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacionesApp', '0004_remove_autor_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(max_length=200, upload_to='', verbose_name='Imagen de Perfil'),
        ),
    ]
