# Generated by Django 4.0.1 on 2022-04-11 22:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicacionesApp', '0006_alter_autor_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
    ]
