# Generated by Django 4.0.1 on 2022-04-12 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacionesApp', '0012_alter_post_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='conocimientos',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='estudios',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='universidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='autor',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
