# Generated by Django 4.0.1 on 2022-04-19 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicacionesApp', '0013_autor_conocimientos_autor_estudios_autor_universidad_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentarios',
        ),
    ]
