# Generated by Django 4.0.1 on 2022-05-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacionesApp', '0015_alter_post_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='disponibilidad',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='precio',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
    ]
