# Generated by Django 4.0.1 on 2022-05-14 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacionesApp', '0017_solicitudes'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudes',
            name='usuario',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
