# Generated by Django 4.0.1 on 2022-05-14 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacionesApp', '0018_solicitudes_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudes',
            name='descripcion',
            field=models.TextField(default=None, max_length=500),
            preserve_default=False,
        ),
    ]
