# Generated by Django 4.0.1 on 2022-05-14 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicacionesApp', '0019_solicitudes_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudes',
            old_name='post',
            new_name='postS',
        ),
    ]
