# Generated by Django 4.0.1 on 2022-05-14 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacionesApp', '0020_rename_post_solicitudes_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='postS',
            field=models.IntegerField(),
        ),
    ]
