# Generated by Django 4.0.1 on 2022-05-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacionesApp', '0021_alter_solicitudes_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudes',
            name='ofertante',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
