# Generated by Django 4.0.1 on 2022-05-15 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicacionesApp', '0022_solicitudes_ofertante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='postS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicacionesApp.post'),
        ),
    ]
