# Generated by Django 4.0.1 on 2022-04-09 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsuariosApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='', verbose_name='Imagen de Perfil'),
        ),
    ]
