# Generated by Django 4.0.1 on 2022-04-10 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UsuariosApp', '0003_alter_usuario_options_usuario_activation_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='activation_key',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='key_expires',
        ),
    ]
