# Generated by Django 4.0.1 on 2022-04-10 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UsuariosApp', '0004_remove_usuario_activation_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user_permissions',
        ),
    ]
