# Generated by Django 4.0.1 on 2022-04-10 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsuariosApp', '0005_remove_usuario_groups_remove_usuario_is_staff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='is_active',
            new_name='usuario_activo',
        ),
        migrations.AddField(
            model_name='usuario',
            name='usuario_admin',
            field=models.BooleanField(default=False),
        ),
    ]
