# Generated by Django 4.0.1 on 2022-04-28 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UsuariosApp', '0008_usuario_groups_usuario_is_superuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='usuario_admin',
            new_name='is_staff',
        ),
    ]
