# Generated by Django 4.0.1 on 2022-04-19 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentariosApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentarios',
            old_name='inmuebles',
            new_name='autores',
        ),
    ]
